# Jupyter

`shift` + `tab` to see docstring and to autocomplete methods.

# Python

## List Comprehension

List comprehension is a way to create a list with values that follow a pattern without using a for loop. It's kinda like a backwards for loop.

In [1]:
s = [x*2 for x in range(4)]
print(s)

[0, 2, 4, 6]


## Lambda Expressions

Lambda expressions are also called anonymous functions. They're pretty much functions with no names.

In [2]:
lambda x:x*2

<function __main__.<lambda>(x)>

You use lambda expressions in functions like `map` and `filter` when you don't want to define new functions.

In [3]:
list(map(lambda x:x**2, range(5)))

[0, 1, 4, 9, 16]

In [4]:
list(filter(lambda x:x%2==0, range(10)))

[0, 2, 4, 6, 8]

## Tuple Unpacking

Tuple unpacking is used when using a for loop to iterate through a list of tuples.

In [5]:
x = [(1,2), (3,4), (5,6)]

for a,b in x:
    print(a)

1
3
5


# NumPy

In [6]:
import numpy as np

## Creating Arrays From Lists

To create an array from a list (or list of lists), pass in the list (or list of lists).

In [7]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [8]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Arrays Using Built-In Methods

### `arange()`

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `zeros()`

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `ones()`

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `linspace()`

In [14]:
# start (inclusive)
# stop (inclusive)
# [number of points]

np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

### `eye()`

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `random.rand()`

Returns numbers from a uniform distribution over [0, 1).

In [16]:
np.random.rand(4)

array([0.16453692, 0.88090461, 0.34999913, 0.02557563])

In [17]:
np.random.rand(3,3)

array([[0.0986996 , 0.35154578, 0.04483473],
       [0.48399684, 0.19689701, 0.81076455],
       [0.73242824, 0.23736365, 0.50152848]])

### `random.randn()`

Returns numbers from a standard normal distribution centered at 0.

In [18]:
np.random.randn(3)

array([-0.83665897, -0.77875953, -0.82870008])

In [19]:
np.random.randn(3,3)

array([[ 1.5250535 ,  0.46595726, -0.29051848],
       [ 0.42133261,  0.21570161,  0.98772491],
       [-0.32404102, -0.1846767 , -2.54461311]])

### `random.randint()`

In [20]:
# low (inclusive)
# [high] (exclusive)
# [number] of integers

np.random.randint(1,50,3)

array([11, 29, 33])

## Array Methods

### `reshape()`

In [21]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

---

In [23]:
b = np.random.randint(0,50,10)

### `max()`

In [24]:
print(b)
b.max()

[26 38 39  1 13  3 42 14 48 16]


48

### `min()`

In [25]:
print(b)
b.min()

[26 38 39  1 13  3 42 14 48 16]


1

### `argmax()`

Returns index location of max value.

In [26]:
print(b)
b.argmax()

[26 38 39  1 13  3 42 14 48 16]


8

### `argmin()`

Returns index location of min value.

In [27]:
print(b)
b.argmin()

[26 38 39  1 13  3 42 14 48 16]


3

### `shape`

In [28]:
print(a)
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(25,)

In [29]:
print(b)
b.shape

[26 38 39  1 13  3 42 14 48 16]


(10,)

In [30]:
c = a.reshape(5,5)
print(c)
c.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

### `dtype`

In [31]:
a.dtype

dtype('int64')

### `copy()`

In [32]:
a_copy = a.copy()
print(a_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


## Array Indexing

We can use single brackets to index into a 2D array by using a comma.

In [33]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
mat[2,1]

8

### Conditional Indexing

We can use boolean arrays to grab values from an array that satisfy a condition.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
boo = arr > 5
boo

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr[boo]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

## Universal Functions

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

A universal function is a function that operates on an array element-by-element.

In [39]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### `sqrt()`

In [40]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

### `exp()`

In [41]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

### `sin()`

In [42]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

### `log()`

In [43]:
np.log(a)

/home/alanlam00/miniconda3/envs/tf/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Pandas

In [44]:
import pandas as pd

## Series

A Series is like a table with two columns, where the first column is the indices and the second column is the data.

### Creating Series From Lists

In [45]:
labels = ['a', 'b', 'c']
data = [1, 2, 3]

pd.Series(data, labels)

a    1
b    2
c    3
dtype: int64

### Creating Series From NumPy Arrays

In [46]:
pd.Series(np.array(data), labels)

a    1
b    2
c    3
dtype: int64

### Creating Series From Dictionaries

In [47]:
d = {'a':1, 'b':2, 'c':3}

pd.Series(d)

a    1
b    2
c    3
dtype: int64

## DataFrames

A DataFrame is a bunch of Series with shared indices.

### Creating DataFrames

When manually creating a DataFrame, the order is `data, row names, column names`.

In [48]:
df = pd.DataFrame(np.random.randint(1,100,20).reshape(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df

W   X   Y   Z
A  29  74   6  17
B  44  95  31  64
C  51   6  46  11
D  47  78  56  69
E  21  71  99  56

### Grabbing Columns

In [49]:
df['W']

A    29
B    44
C    51
D    47
E    21
Name: W, dtype: int64

To grab multiple columns, pass in a list of the column names.

In [50]:
df[['W', 'Y']]

W   Y
A  29   6
B  44  31
C  51  46
D  47  56
E  21  99

### Adding New Columns

In [51]:
df['&'] = np.random.randint(1,100,5)
df

W   X   Y   Z   &
A  29  74   6  17  11
B  44  95  31  64  77
C  51   6  46  11  77
D  47  78  56  69  99
E  21  71  99  56  28

### Removing Columns

In [52]:
df.drop('&', axis=1, inplace=True) # inplace changes dataframe directly
df

W   X   Y   Z
A  29  74   6  17
B  44  95  31  64
C  51   6  46  11
D  47  78  56  69
E  21  71  99  56

### Removing Rows

In [53]:
df.drop('E')

W   X   Y   Z
A  29  74   6  17
B  44  95  31  64
C  51   6  46  11
D  47  78  56  69

### Grabbing Rows

We can use `loc` and pass in the name of the row.

In [54]:
df.loc['A']

W    29
X    74
Y     6
Z    17
Name: A, dtype: int64

Or we can use `iloc` and pass in the index of the row.

In [55]:
df.iloc[0]

W    29
X    74
Y     6
Z    17
Name: A, dtype: int64

### Grabbing Single Values

To grab a single value, specify the name of the row and the name of the column separated by a comma.

In [56]:
df.loc['B','Z']

64

### Grabbing Subsets

To grab a subset of the dataframe, pass in a list of the row names and a list of the column names separated by a comma.

In [57]:
df.loc[['A','C'],['X','Y']]

X   Y
A  74   6
C   6  46

### Conditional Selection

In [58]:
df[df % 2 == 0]

W     X     Y     Z
A   NaN  74.0   6.0   NaN
B  44.0   NaN   NaN  64.0
C   NaN   6.0  46.0   NaN
D   NaN  78.0  56.0   NaN
E   NaN   NaN   NaN  56.0

In [59]:
df[df['W'] % 2 == 0] # return rows where number in W is even

W   X   Y   Z
B  44  95  31  64

To use multiple conditions, use an ampersand `&` or pipe operator `|`.

In [60]:
df[(df['W'] % 2 == 0) | (df['Y'] > 0)]

W   X   Y   Z
A  29  74   6  17
B  44  95  31  64
C  51   6  46  11
D  47  78  56  69
E  21  71  99  56

### Changing Indices

We can change the indices back to the default indexing.

In [61]:
df.reset_index(inplace=True)
df

index   W   X   Y   Z
0     A  29  74   6  17
1     B  44  95  31  64
2     C  51   6  46  11
3     D  47  78  56  69
4     E  21  71  99  56

If there's a column that we want to use as the new indices, we can set the index by passing in the column name.

In [62]:
df.set_index('index')

W   X   Y   Z
index                
A      29  74   6  17
B      44  95  31  64
C      51   6  46  11
D      47  78  56  69
E      21  71  99  56

### Multi-Index And Index Hierarchy

A Dataframe can have multiple levels of indices.

In [63]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [64]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [65]:
df = pd.DataFrame(np.random.randn(6,2), hier_index, ['A','B'])
df

A         B
G1 1  0.555096 -1.310181
   2  0.770070 -0.031162
   3 -0.584275  0.089460
G2 1  1.725774  0.846736
   2  0.013789 -0.085394
   3 -0.097053 -1.531582

In [66]:
df.loc['G1']

A         B
1  0.555096 -1.310181
2  0.770070 -0.031162
3 -0.584275  0.089460

In [67]:
df.loc['G1'].loc[1]

A    0.555096
B   -1.310181
Name: 1, dtype: float64

To add index names, create a list with the names of the index columns.

In [68]:
df.index.names = ['Groups', 'Numbers']
df

A         B
Groups Numbers                    
G1     1        0.555096 -1.310181
       2        0.770070 -0.031162
       3       -0.584275  0.089460
G2     1        1.725774  0.846736
       2        0.013789 -0.085394
       3       -0.097053 -1.531582

We can grab a cross-section of the DataFrame to grab some rows from each index. To do that, we specify the name of the row and the name of the column in which it exists.

In [69]:
df.xs(1, level='Numbers')

A         B
Groups                    
G1      0.555096 -1.310181
G2      1.725774  0.846736

### Missing Data

In [70]:
d = {'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1, 2, 3]}
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [71]:
df.dropna() # drop rows with NaN values

A    B  C
0  1.0  5.0  1

In [72]:
df.dropna(thresh=2) # drop rows with less than 2 NaN values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [73]:
df.fillna(value=df['A'].mean()) # replace NaN with mean of Column A

A    B  C
0  1.0  5.0  1
1  2.0  1.5  2
2  1.5  1.5  3

### Groupby

Groupby grabs rows with the same values and puts them in a group. That way, we can apply aggregate functions to that group.

An aggregate function takes in many inputs and returns a single value. Some examples are taking the sum, average, and standard deviation.

In [74]:
d = {'Team':['A', 'A', 'B', 'B', 'C', 'C'],
     'Leader':['QWE', 'RTY', 'UIO', 'OPA', 'SDF', 'GHJ'],
     'Points':[200, 150, 198, 256, 20, 179]}

df = pd.DataFrame(d)
df

Team Leader  Points
0    A    QWE     200
1    A    RTY     150
2    B    UIO     198
3    B    OPA     256
4    C    SDF      20
5    C    GHJ     179

In [75]:
df.groupby('Team').sum()

Points
Team        
A        350
B        454
C        199

In [76]:
df.groupby('Team').max() # Note: returns max of each column

Leader  Points
Team               
A       RTY     200
B       UIO     256
C       SDF     179

In [77]:
df.groupby('Team').describe()

Points                                                        
      count   mean         std    min     25%    50%     75%    max
Team                                                               
A       2.0  175.0   35.355339  150.0  162.50  175.0  187.50  200.0
B       2.0  227.0   41.012193  198.0  212.50  227.0  241.50  256.0
C       2.0   99.5  112.429978   20.0   59.75   99.5  139.25  179.0

To get information for one team, transpose then grab the column.

In [78]:
df.groupby('Team').describe().transpose()

Team                   A           B           C
Points count    2.000000    2.000000    2.000000
       mean   175.000000  227.000000   99.500000
       std     35.355339   41.012193  112.429978
       min    150.000000  198.000000   20.000000
       25%    162.500000  212.500000   59.750000
       50%    175.000000  227.000000   99.500000
       75%    187.500000  241.500000  139.250000
       max    200.000000  256.000000  179.000000

### Concatenating DataFrames

In [79]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [80]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [81]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

To concatenate DataFrames together, pass in a list with the names of the DataFrames to `concat()`.

In [82]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

### Merging DataFrames

Merging DataFrames combines DataFrames where the columns are the same.

In [83]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [84]:
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

If we just concatenate, then the column will show up multiple times.

In [85]:
pd.concat([left, right], axis=1)

key   A   B key   C   D
0  K0  A0  B0  K0  C0  D0
1  K1  A1  B1  K1  C1  D1
2  K2  A2  B2  K2  C2  D2
3  K3  A3  B3  K3  C3  D3

If we merge, then the columns will merge into one column.

In [86]:
pd.merge(left, right, on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

We can merge using multiple columns. Then only the rows where all the columns match are kept.

In [87]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
left

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [88]:
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})
right

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [89]:
pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

### Joining DataFrames

Join is like merge except that the keys we want to merge on are the indices.

In [90]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [91]:
right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [92]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

### Finding Unique Values

In [93]:
df = pd.DataFrame({'col1': [1,2,3,4],
                   'col2': [444,555,666,444],
                   'col3': ['abc', 'def', 'ghi', 'xyz']})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

#### `unique()`

In [94]:
df['col2'].unique()

array([444, 555, 666])

#### `nunique()`

In [95]:
df['col2'].nunique()

3

#### `value_counts()`

In [96]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

### Removing Columns

In [97]:
df.drop('col1', axis=1)

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

### Sorting

In [98]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

### Pivot Table

A pivot table is a multi-index DataFrame. (?)

In [99]:
df = pd.DataFrame({'A':['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
                   'B':['one', 'one', 'two', 'two', 'one', 'one'],
                   'C':['x', 'y', 'x', 'y', 'x', 'y'],
                   'D':[1, 3, 2, 5, 4, 1]})
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [100]:
df.pivot_table(values='D', index=['A','B'], columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN