# Jupyter

`shift` + `tab` to see docstring

# Python

## List Comprehension

List comprehension is a way to create a list with values that follow a pattern without using a for loop. It's kinda like a backwards for loop.

In [1]:
s = [x*2 for x in range(4)]
print(s)

[0, 2, 4, 6]


## Lambda Expressions

Lambda expressions are also called anonymous functions. They're pretty much functions with no names.

In [2]:
lambda x:x*2

<function __main__.<lambda>(x)>

You use lambda expressions in functions like `map` and `filter` when you don't want to define new functions.

In [3]:
list(map(lambda x:x**2, range(5)))

[0, 1, 4, 9, 16]

In [4]:
list(filter(lambda x:x%2==0, range(10)))

[0, 2, 4, 6, 8]

## Tuple Unpacking

Tuple unpacking is used when using a for loop to iterate through a list of tuples.

In [5]:
x = [(1,2), (3,4), (5,6)]

for a,b in x:
    print(a)

1
3
5


# NumPy

In [6]:
import numpy as np

## Creating Arrays From Lists

To create an array from a list (or list of lists), pass in the list (or list of lists).

In [7]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [8]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Arrays Using Built-In Methods

### `arange()`

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `zeros()`

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `ones()`

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `linspace()`

In [14]:
# start (inclusive)
# stop (inclusive)
# [number of points]

np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

### `eye()`

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `random.rand()`

Returns numbers from a uniform distribution over [0, 1).

In [16]:
np.random.rand(4)

array([0.46351837, 0.31296391, 0.06651491, 0.69151313])

In [17]:
np.random.rand(3,3)

array([[0.48297518, 0.80698235, 0.25326791],
       [0.68257281, 0.70739372, 0.55228128],
       [0.19381375, 0.75238264, 0.34903967]])

### `random.randn()`

Returns numbers from a standard normal distribution centered at 0.

In [18]:
np.random.randn(3)

array([ 0.75608524,  0.40497327, -0.00455613])

In [19]:
np.random.randn(3,3)

array([[-0.44735846,  2.43389879,  0.35475415],
       [-0.42081826,  0.74148039,  2.48387627],
       [-0.20310961, -0.73551151,  1.18707852]])

### `random.randint()`

In [20]:
# low (inclusive)
# [high] (exclusive)
# [number] of integers

np.random.randint(1,50,3)

array([18, 48, 24])

## Array Methods

### `reshape()`

In [21]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

---

In [23]:
b = np.random.randint(0,50,10)

### `max()`

In [24]:
print(b)
b.max()

[34 43 42  6 22 12 40 42 20 15]


43

### `min()`

In [25]:
print(b)
b.min()

[34 43 42  6 22 12 40 42 20 15]


6

### `argmax()`

Returns index location of max value.

In [26]:
print(b)
b.argmax()

[34 43 42  6 22 12 40 42 20 15]


1

### `argmin()`

Returns index location of min value.

In [27]:
print(b)
b.argmin()

[34 43 42  6 22 12 40 42 20 15]


3

### `shape`

In [28]:
print(a)
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(25,)

In [29]:
print(b)
b.shape

[34 43 42  6 22 12 40 42 20 15]


(10,)

In [30]:
c = a.reshape(5,5)
print(c)
c.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

### `dtype`

In [31]:
a.dtype

dtype('int64')

### `copy()`

In [32]:
a_copy = a.copy()
print(a_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


## Array Indexing

We can use single brackets to index into a 2D array by using a comma.

In [33]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
mat[2,1]

8

### Conditional Indexing

We can use boolean arrays to grab values from an array that satisfy a condition.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
boo = arr > 5
boo

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr[boo]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

## Universal Functions

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

A universal function is a function that operates on an array element-by-element.

In [39]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### `sqrt()`

In [40]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

### `exp()`

In [41]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

### `sin()`

In [42]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

### `log()`

In [43]:
np.log(a)

/home/alanlam00/miniconda3/envs/tf/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Pandas

In [44]:
import pandas as pd

## Series

A Series is like a table with two columns, where the first column is the indices and the second column is the data.

### Creating Series From Lists

In [45]:
labels = ['a', 'b', 'c']
data = [1, 2, 3]

pd.Series(data, labels)

a    1
b    2
c    3
dtype: int64

### Creating Series From NumPy Arrays

In [46]:
pd.Series(np.array(data), labels)

a    1
b    2
c    3
dtype: int64

### Creating Series From Dictionaries

In [47]:
d = {'a':1, 'b':2, 'c':3}

pd.Series(d)

a    1
b    2
c    3
dtype: int64

## DataFrames

A DataFrame is a bunch of Series with shared indices.

### Creating DataFrames

When manually creating a DataFrame, the order is `data, row names, column names`.

In [48]:
df = pd.DataFrame(np.random.randint(1,100,20).reshape(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df

W   X   Y   Z
A   4  62  12  50
B  78  55  36  37
C   3  89   6  87
D  91  74  49  28
E  43  81  35  55

### Grabbing Columns

In [49]:
df['W']

A     4
B    78
C     3
D    91
E    43
Name: W, dtype: int64

To grab multiple columns, pass in a list of the column names.

In [50]:
df[['W', 'Y']]

W   Y
A   4  12
B  78  36
C   3   6
D  91  49
E  43  35

### Adding New Columns

In [51]:
df['&'] = np.random.randint(1,100,5)
df

W   X   Y   Z   &
A   4  62  12  50  43
B  78  55  36  37  30
C   3  89   6  87  98
D  91  74  49  28   9
E  43  81  35  55  82

### Removing Columns

In [52]:
df.drop('&', axis=1, inplace=True) # inplace changes dataframe directly
df

W   X   Y   Z
A   4  62  12  50
B  78  55  36  37
C   3  89   6  87
D  91  74  49  28
E  43  81  35  55

### Removing Rows

In [53]:
df.drop('E')

W   X   Y   Z
A   4  62  12  50
B  78  55  36  37
C   3  89   6  87
D  91  74  49  28

### Grabbing Rows

We can use `loc` and pass in the name of the row.

In [54]:
df.loc['A']

W     4
X    62
Y    12
Z    50
Name: A, dtype: int64

Or we can use `iloc` and pass in the index of the row.

In [55]:
df.iloc[0]

W     4
X    62
Y    12
Z    50
Name: A, dtype: int64

### Grabbing Single Values

To grab a single value, specify the name of the row and the name of the column separated by a comma.

In [56]:
df.loc['B','Z']

37

### Grabbing Subsets

To grab a subset of the dataframe, pass in a list of the row names and a list of the column names separated by a comma.

In [57]:
df.loc[['A','C'],['X','Y']]

X   Y
A  62  12
C  89   6

### Conditional Selection

In [58]:
df[df % 2 == 0]

W     X     Y     Z
A   4.0  62.0  12.0  50.0
B  78.0   NaN  36.0   NaN
C   NaN   NaN   6.0   NaN
D   NaN  74.0   NaN  28.0
E   NaN   NaN   NaN   NaN

In [59]:
df[df['W'] % 2 == 0]

W   X   Y   Z
A   4  62  12  50
B  78  55  36  37

To use multiple conditions, use an ampersand `&` or pipe operator `|`.

In [60]:
df[(df['W'] % 2 == 0) | (df['Y'] > 0)]

W   X   Y   Z
A   4  62  12  50
B  78  55  36  37
C   3  89   6  87
D  91  74  49  28
E  43  81  35  55

### Changing Indices

We can change the indices back to the default indexing.

In [61]:
df.reset_index(inplace=True)
df

index   W   X   Y   Z
0     A   4  62  12  50
1     B  78  55  36  37
2     C   3  89   6  87
3     D  91  74  49  28
4     E  43  81  35  55

If there's a column that we want to use as the new indices, we can set the index by passing in the column name.

In [62]:
df.set_index('index')

W   X   Y   Z
index                
A       4  62  12  50
B      78  55  36  37
C       3  89   6  87
D      91  74  49  28
E      43  81  35  55