# Jupyter

`shift + tab` to see docstring

# Python

## List Comprehension

List comprehension is a way to create a list with values that follow a pattern without using a for loop. It's kinda like a backwards for loop.

In [4]:
s = [x*2 for x in range(4)]
print(s)

[0, 2, 4, 6]


## Lambda Expressions

Lambda expressions are also called anonymous functions. They're kinda like functions with no names.

In [ ]:
lambda x:x*2

You use lambda expressions in functions like `map` and `filter` when you don't want to define new functions.

In [6]:
list(map(lambda x:x**2, range(5)))

[0, 1, 4, 9, 16]

In [8]:
list(filter(lambda x:x%2==0, range(10)))

[0, 2, 4, 6, 8]

## Tuple Unpacking

Tuple unpacking is used when using a for loop to iterate through a list of tuples.

In [9]:
x = [(1,2), (3,4), (5,6)]

for a,b in x:
    print(a)

1
3
5


# NumPy

## Creating Arrays From Lists

In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [3]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Arrays Using Built-In Methods

### `arange()`

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `zeros()`

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `ones()`

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `linspace()`

In [14]:
# start (inclusive)
# stop (inclusive)
# [number of points]

np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

### `eye()`

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `random.rand()`

This returns numbers from a uniform distribution over [0, 1).

In [16]:
np.random.rand(4)

array([0.24093692, 0.19465001, 0.62559639, 0.32229114])

In [18]:
np.random.rand(3,3)

array([[0.79904694, 0.20141129, 0.16184872],
       [0.26264619, 0.94318371, 0.08881037],
       [0.16432431, 0.46940965, 0.39569819]])

### `random.randn()`

This returns numbers from a standard normal distribution centered at 0.

In [21]:
np.random.randn(3)

array([-0.28596867, -0.27970339,  0.41138631])

In [20]:
np.random.randn(3,3)

array([[-0.43766584,  1.29161856,  0.39418082],
       [-0.0081121 , -1.27429844, -0.66625682],
       [ 0.08850024, -0.18732976, -0.3615857 ]])

### `random.randint()`

In [27]:
# low (inclusive)
# [high] (exclusive)
# [number] of integers

np.random.randint(1,50,3)

array([ 2, 36,  3])

## Array Operations

In [ ]:
a = np.arange(25)
b = np.random.randint(0,50,10)