# Jupyter

`shift` + `tab` to see docstring

# Python

## List Comprehension

List comprehension is a way to create a list with values that follow a pattern without using a for loop. It's kinda like a backwards for loop.

In [1]:
s = [x*2 for x in range(4)]
print(s)

[0, 2, 4, 6]


## Lambda Expressions

Lambda expressions are also called anonymous functions. They're pretty much functions with no names.

In [2]:
lambda x:x*2

<function __main__.<lambda>(x)>

You use lambda expressions in functions like `map` and `filter` when you don't want to define new functions.

In [3]:
list(map(lambda x:x**2, range(5)))

[0, 1, 4, 9, 16]

In [4]:
list(filter(lambda x:x%2==0, range(10)))

[0, 2, 4, 6, 8]

## Tuple Unpacking

Tuple unpacking is used when using a for loop to iterate through a list of tuples.

In [5]:
x = [(1,2), (3,4), (5,6)]

for a,b in x:
    print(a)

1
3
5


# NumPy

In [6]:
import numpy as np

## Creating Arrays From Lists

To create an array from a list (or list of lists), pass in the list (or list of lists).

In [7]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [8]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Arrays Using Built-In Methods

### `arange()`

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `zeros()`

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `ones()`

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `linspace()`

In [14]:
# start (inclusive)
# stop (inclusive)
# [number of points]

np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

### `eye()`

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `random.rand()`

Returns numbers from a uniform distribution over [0, 1).

In [16]:
np.random.rand(4)

array([0.08178209, 0.42263013, 0.51919693, 0.19203198])

In [17]:
np.random.rand(3,3)

array([[0.47253511, 0.83882542, 0.22351829],
       [0.216232  , 0.99199994, 0.4826512 ],
       [0.74581704, 0.55345909, 0.46294661]])

### `random.randn()`

Returns numbers from a standard normal distribution centered at 0.

In [18]:
np.random.randn(3)

array([-0.68533018, -0.87865597,  0.13175223])

In [19]:
np.random.randn(3,3)

array([[-0.65553194,  0.04860013, -0.08010878],
       [ 0.21944083,  0.38027019, -0.13966856],
       [ 1.17484679,  0.87603379, -1.06206248]])

### `random.randint()`

In [20]:
# low (inclusive)
# [high] (exclusive)
# [number] of integers

np.random.randint(1,50,3)

array([36, 40, 44])

## Array Methods

### `reshape()`

In [21]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

---

In [23]:
b = np.random.randint(0,50,10)

### `max()`

In [24]:
print(b)
b.max()

[28 27 13 36 10  6 32 19 26  5]


36

### `min()`

In [25]:
print(b)
b.min()

[28 27 13 36 10  6 32 19 26  5]


5

### `argmax()`

Returns index location of max value.

In [26]:
print(b)
b.argmax()

[28 27 13 36 10  6 32 19 26  5]


3

### `argmin()`

Returns index location of min value.

In [27]:
print(b)
b.argmin()

[28 27 13 36 10  6 32 19 26  5]


9

### `shape`

In [28]:
print(a)
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(25,)

In [29]:
print(b)
b.shape

[28 27 13 36 10  6 32 19 26  5]


(10,)

In [30]:
c = a.reshape(5,5)
print(c)
c.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

### `dtype`

In [31]:
a.dtype

dtype('int64')

### `copy()`

In [32]:
a_copy = a.copy()
print(a_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


## Array Indexing

We can use single brackets to index into a 2D array by using a comma.

In [33]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
mat[2,1]

8

### Conditional Indexing

We can use boolean arrays to grab values from an array that satisfy a condition.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
boo = arr > 5
boo

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
arr[boo]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

## Universal Functions

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

A universal function is a function that operates on an array element-by-element.

In [39]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### `sqrt()`

In [40]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

### `exp()`

In [41]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

### `sin()`

In [42]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

### `log()`

In [43]:
np.log(a)

/home/alanlam00/miniconda3/envs/tf/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Pandas

In [44]:
import pandas as pd

## Series

A Series is like a table with two columns, where the first column is the indices and the second column is the data.

### Creating Series From Lists

In [45]:
labels = ['a', 'b', 'c']
data = [1, 2, 3]

pd.Series(data, labels)

a    1
b    2
c    3
dtype: int64

### Creating Series From NumPy Arrays

In [46]:
pd.Series(np.array(data), labels)

a    1
b    2
c    3
dtype: int64

### Creating Series From Dictionaries

In [47]:
d = {'a':1, 'b':2, 'c':3}

pd.Series(d)

a    1
b    2
c    3
dtype: int64

## DataFrames

A DataFrame is a bunch of Series with shared indices.

### Creating DataFrames

When manually creating a DataFrame, the order is `data, row names, column names`.

In [48]:
df1 = pd.DataFrame(np.random.randint(1,100,20).reshape(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df1

W   X   Y   Z
A  11  40  22  91
B  94  41  96  68
C  93  67  87  19
D  38  92  91  12
E  58  29   7  33

### Grabbing Columns

In [49]:
df1['W']

A    11
B    94
C    93
D    38
E    58
Name: W, dtype: int64

To grab multiple columns, pass in a list of the column names.

In [50]:
df1[['W', 'Y']]

W   Y
A  11  22
B  94  96
C  93  87
D  38  91
E  58   7

### Adding New Columns

In [51]:
df1['&'] = np.random.randint(1,100,5)
df1

W   X   Y   Z   &
A  11  40  22  91  69
B  94  41  96  68   4
C  93  67  87  19  81
D  38  92  91  12  10
E  58  29   7  33  18

### Removing Columns

In [52]:
df1.drop('&', axis=1, inplace=True) # inplace changes dataframe directly
df1

W   X   Y   Z
A  11  40  22  91
B  94  41  96  68
C  93  67  87  19
D  38  92  91  12
E  58  29   7  33

### Removing Rows

In [53]:
df1.drop('E')

W   X   Y   Z
A  11  40  22  91
B  94  41  96  68
C  93  67  87  19
D  38  92  91  12

### Grabbing Rows

We can use `loc` and pass in the name of the row.

In [55]:
df1.loc['A']

W    11
X    40
Y    22
Z    91
Name: A, dtype: int64

Or we can use `iloc` and pass in the index of the row.

In [57]:
df1.iloc[0]

W    11
X    40
Y    22
Z    91
Name: A, dtype: int64

### Grabbing Single Values

To grab a single value, specify the name of the row and the name of the column separated by a comma.

In [58]:
df1.loc['B','Z']

68

### Grabbing Subsets

To grab a subset of the dataframe, pass in a list of the row names and a list of the column names separated by a comma.

In [59]:
df1.loc[['A','C'],['X','Y']]

X   Y
A  40  22
C  67  87