# Jupyter

`shift + tab` to see docstring

# Python

## List Comprehension

List comprehension is a way to create a list with values that follow a pattern without using a for loop. It's kinda like a backwards for loop.

In [1]:
s = [x*2 for x in range(4)]
print(s)

[0, 2, 4, 6]


## Lambda Expressions

Lambda expressions are also called anonymous functions. They're kinda like functions with no names.

In [2]:
lambda x:x*2

<function __main__.<lambda>(x)>

You use lambda expressions in functions like `map` and `filter` when you don't want to define new functions.

In [3]:
list(map(lambda x:x**2, range(5)))

[0, 1, 4, 9, 16]

In [4]:
list(filter(lambda x:x%2==0, range(10)))

[0, 2, 4, 6, 8]

## Tuple Unpacking

Tuple unpacking is used when using a for loop to iterate through a list of tuples.

In [5]:
x = [(1,2), (3,4), (5,6)]

for a,b in x:
    print(a)

1
3
5


# NumPy

## Creating Arrays From Lists

In [6]:
import numpy as np

In [7]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [8]:
mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Arrays Using Built-In Methods

### `arange()`

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `zeros()`

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### `ones()`

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `linspace()`

In [14]:
# start (inclusive)
# stop (inclusive)
# [number of points]

np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

### `eye()`

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### `random.rand()`

Returns numbers from a uniform distribution over [0, 1).

In [16]:
np.random.rand(4)

array([0.39207155, 0.93436439, 0.12690821, 0.96685111])

In [17]:
np.random.rand(3,3)

array([[0.44115342, 0.13388278, 0.2978262 ],
       [0.98941159, 0.19184041, 0.18155843],
       [0.75050653, 0.09910649, 0.93669747]])

### `random.randn()`

Returns numbers from a standard normal distribution centered at 0.

In [18]:
np.random.randn(3)

array([-0.99704568,  0.08833291, -1.18003855])

In [19]:
np.random.randn(3,3)

array([[ 0.25942817,  0.25043778, -0.50019637],
       [-0.19791146, -0.26188848,  0.26595345],
       [-0.69642047,  1.26457878, -0.20960642]])

### `random.randint()`

In [20]:
# low (inclusive)
# [high] (exclusive)
# [number] of integers

np.random.randint(1,50,3)

array([21, 18, 31])

## Array Operations

### `reshape()`

In [21]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
b = np.random.randint(0,50,10)

### `max()`

In [24]:
print(b)
b.max()

[47 16 48  3 45 18  0  6 17  9]


48

### `min()`

In [25]:
print(b)
b.min()

[47 16 48  3 45 18  0  6 17  9]


0

### `argmax()`

Returns index location of max value.

In [26]:
print(b)
b.argmax()

[47 16 48  3 45 18  0  6 17  9]


2

### `argmin()`

Returns index location of min value.

In [27]:
print(b)
b.argmin()

[47 16 48  3 45 18  0  6 17  9]


6

### `shape`

In [28]:
print(a)
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


(25,)

In [29]:
print(b)
b.shape

[47 16 48  3 45 18  0  6 17  9]


(10,)

In [30]:
c = a.reshape(5,5)
print(c)
c.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

### `dtype`

In [31]:
a.dtype

dtype('int64')