# NumPy

## Creating Arrays

### `arange()`

In [1]:
import numpy as np

a = np.arange(10)
print(a)

print()

b = np.arange(0,10,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]


### `zeros()`

In [2]:
import numpy as np

a = np.zeros(5)
print(a)

print()

# 1: tuple (rows, cols)
# return: list of lists of zeros
b = np.zeros((2,3))
print(b)

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


### `full()`

In [3]:
import numpy as np

# 1: tuple (rows, cols)
# 2: int - number with which to fill matrix
# return: list of lists filled with a number
a = np.full((2,3), 8)
print(a)

[[8 8 8]
 [8 8 8]]


### `eye()`

In [4]:
import numpy as np

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### `random()`

In [5]:
import numpy as np

# [0.0, 1.0)

# 1: tuple (rows, cols)
# return: list of lists - random numbers
a = np.random.random((2,4))
print(a)

[[0.72908206 0.47612379 0.09910415 0.85949188]
 [0.78493114 0.82276172 0.87089575 0.15377023]]


### `array()`

In [6]:
import numpy as np

listy = [1, 2, 3, 4, 5]

a = np.array(listy)
print(a)

[1 2 3 4 5]


In [7]:
import numpy as np

list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 0]

# 1: list [first list, second list, ...]
# return: list of lists
a = np.array([list1, list2])
print(a)

[[1 2 3 4 5]
 [6 7 8 9 0]]


## Array Indexing

In [8]:
import numpy as np

a = [1, 2, 3, 4, 5]

print(a[0])

1


In [9]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 0]
c = np.array([a,b])

print(c[0,0])

1


In [10]:
import numpy as np

a = [1, 2, 3, 4, 5]
c = np.array(a)

print(c[[2,4]])

[3 5]


### Boolean Indexing

In [11]:
import numpy as np

a = [1, 2, 3, 4, 5]
c = np.array(a)

print(c > 2)

print()

print(c[c > 2])

[False False  True  True  True]

[3 4 5]


### Slicing Arrays

In [12]:
import numpy as np

a = np.arange(20)
odd_nums = a[a % 2 == 1]

print(odd_nums)

[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
b = a[1:3, :3]

print(b)

print()

c = a[-2:, -2:]
print(c)

[[4 5 6]
 [9 8 7]]

[[7 8]
 [6 5]]


Slicing returns a reference (not a copy) to the original array

In [14]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
b = a[1:, 2:]

print(b)

print()

b[0,2] = 88

print(a)

[[6 7 8]
 [7 6 5]]

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


Result of slicing is dependent on how it is sliced

In [15]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
b = a[2:, :]

print(b)
print(b.shape)

print()

c = a[2, :]

print(c)
print(c.shape)

[[9 8 7 6 5]]
(1, 5)

[9 8 7 6 5]
(5,)


## Reshaping Arrays

### `reshape()`

In [16]:
# convert rank 1 array to rank 2

import numpy as np

a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
b = a[2, :]

print(b)

print()

# 1: int - rows
# 2: int - cols (-1 means automatically determine)
b = b.reshape(1, -1) 
print(b)
# output is same as reshape(1,5)

[9 8 7 6 5]

[[9 8 7 6 5]]


In [17]:
# convert rank 2 array to rank 1

import numpy as np

a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])
b = a[2:, :]

print(b)

print()

b = b.reshape(-1,)
print(b)

[[9 8 7 6 5]]

[9 8 7 6 5]


## Array Math

### Addition / Subtraction / Multiplication / Division

In [18]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [2 ,3, 4]])

print(x+y) # same as np.add(x,y)
print()
print(x-y) # same as np.subtract(x,y)
print()
print(x*y) # same as np.multiply(x,y)
print()
print(x/y) # same as np.divide(x,y)

[[ 8 10 12]
 [ 6  8 10]]

[[-6 -6 -6]
 [ 2  2  2]]

[[ 7 16 27]
 [ 8 15 24]]

[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


### Dot Product

### `dot()`

In [19]:
import numpy as np

x = np.array([2, 3])
y = np.array([4, 2])

print(np.dot(x,y)) # 2*4 + 3*2

14


A dot product of two rank 2 arrays is the same as matrix multiplication

In [20]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8], [9, 10], [11, 12]])

print(np.dot(x,y))

[[ 58  64]
 [139 154]]


## Matrix

Matrices are two-dimensional while `ndarrays` are multidimensional

In [21]:
import numpy as np

x = np.matrix([[1, 2], [4, 5]])

print(x)

[[1 2]
 [4 5]]


In [22]:
# convert NumPy array to matrix

import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.asmatrix(x)

print(y)

[[1 2]
 [3 4]]


When multiplying two `ndarray`s, the result is element-wise multiplication.

When multiplying two matrices, the result is the dot product.

In [23]:
import numpy as np

x1 = np.array([[1, 2], [4, 5]])
y1 = np.array([[7, 8], [2, 3]])

print(x*y)

print()

x2 = np.matrix([[1, 2], [4, 5]])
y2 = np.matrix([[7, 8], [2, 3]])

print(x2*y2)

[[ 7 10]
 [15 22]]

[[11 14]
 [38 47]]


## Cumulative Sum

### `cumsum()`

In [24]:
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(a)

print()

print(a.cumsum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1  3  6 10 15 21 28 36 45]


In [25]:
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(a)

print()

print(a.cumsum(axis=0)) # sum over rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [26]:
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(a)

print()

print(a.cumsum(axis=1)) # sum over columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


## Sorting

### `sort()`

In [27]:
import numpy as np

a = np.array([34, 12, 37, 5, 13])

print(np.sort(a)) # does not modify original array

print()

print(a)

[ 5 12 13 34 37]

[34 12 37  5 13]


### `argsort()`

In [28]:
import numpy as np

a = np.array([34, 12, 37, 5, 13])

print(a.argsort()) # returns indices of sorted elements

[3 1 4 0 2]


In [29]:
import numpy as np

persons = np.array(['Fourth', 'Second', 'Fifth', 'First', 'Third'])
ages = np.array([34, 12, 37, 5, 13])

sort_indices = np.argsort(ages)

print(persons[sort_indices])

print()

reverse_sort_indices = np.argsort(ages)[::-1]

print(persons[reverse_sort_indices])

['First' 'Second' 'Third' 'Fourth' 'Fifth']

['Fifth' 'Fourth' 'Third' 'Second' 'First']


## Array Assignment

### Copy by Reference

In [30]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

b = a # b is pointing to a

### Copy by View (Shallow Copy)

Creates a copy by reference, but changing the shape does not change the shape of the original

Values will still change

### `view()`

In [31]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

b = a.view()

a.shape = 1, -1
a[0,0] = 9

print(a)

print()

print(b)

[[9 2 3 4 5 6 7 8]]

[[9 2 3 4]
 [5 6 7 8]]


### Copy by Value (Deep Copy)

### `copy()`

In [32]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

b = a.copy()

a[0][0] = 9

print(a)

print()

print(b)

[[9 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]
